### ISSUE TITLE
bbox definition not strict enough

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-features#401]
The bbox description explicitly states that it's either 4 or 6 elements.

The schema also allows 5 elements:
https://github.com/opengeospatial/ogcapi-features/blob/c6cfa66ac83ab80934e41bb447505e186e4abf11/core/openapi/schemas/extent.yaml#L49

I think
```yaml
        minItems: 4
        maxItems: 6
```

should be replaced with:
```yaml
        oneOf:
        - minItems: 4
          maxItems: 4
        - minItems: 6
          maxItems: 6
```

Same applies to:
https://github.com/opengeospatial/ogcapi-features/blob/5ab193c6e7f8208be2bd5044ff28781a4697c4da/core/openapi/parameters/bbox.yaml#L33
Not sure whether this also applies in other places, too.
