### ISSUE TITLE
Harmonize the "queryables" resource with OGC API Styles

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#424]
See http://docs.opengeospatial.org/DRAFTS/20-009.html#rc_queryables. Both resources have the same role. There should only be a single requirements class for queryables.

**Comment by cportele** [comment]
2020-08-03: @cportele to make a proposal.

**Comment by cportele** [comment]
Link to the section in the document: http://docs.opengeospatial.org/DRAFTS/19-079.html#filter-queryables

Proposal for the schema of the queryables:

```yaml
type: object
required:
- queryables   
properties:
   queryables:
      type: array
      items: 
         type: object
         required:
         - id   
         - type
         properties:
            id:
               description: the token that may be used in a query predicate
               type: string
            title:
               description: a human readable title for the queryable
               type: string
            description:
               description: a human-readable narrative describing the queryable
               type: string
            language:
               description: the language used for the title and description
               type: string
            type:
               description: the data type of the queryable
               type: string
               enum:
               - string
               - number
               - integer
               - boolean
               - spatial
               - temporal
            spatial-types:
               description: the list of allowed spatial geometry types, if known
               enum:
               - point
               - multi-point
               - curve
               - multi-curve
               - surface
               - multi-surface
               - solid
               - multi-solid
               - aggregate
            temporal-types:
               description: the list of allowed temporal geometry types, if known
               enum:
               - instant
               - interval
            links:
               description: additional links, e.g. to documentation or to the schema of the values
               type: array
               items:
                  $ref: 'https://raw.githubusercontent.com/opengeospatial/ogcapi-features/master/core/openapi/ogcapi-features-1.yaml#/components/schemas/link'
```

So the example would change to:

```json
{   
   "queryables": [
      {
         "id": "elevation",
         "title": "Elevation",
         "description": "The average distance of the road segment above sea level in meter.",
         "type": "number"
      },
      {
         "id": "nlanes",
         "title": "Number of lanes",
         "description": "The total number of lanes in all directions.",
         "type": "integer"
      },
      {
         "id": "geom",
         "title": "Segment Geometry",
         "description": "The geometry of the road segment",
         "type": "spatial",
         "spatial-type": "curve"
      },
      {
         "id": "name",
         "title": "Segment Name",
         "description": "The common name of the road segment.",
         "type": "string"
      }
   ]
}
```

Changes:

* Changed `queryable` to `id` to make it consistent with other schemas, e.g. in the Collections resource where `id` is used.
* Provided enums for `type`. The values can be debated, but at least we need to distinguish strings, numbers, boolean, spatial geometries and temporal geometries as these are relevant for filters.
* Added `spatial-type` and `temporal-type` as hints.
* Added a links section so that one can add a link to a JSON schema (`rel: describedby`, `type: application/schema+json`) or human readable documentation, where available.

We should extend the example to cover also a temporal property and links.
