### ISSUE TITLE
Part 3: duplicate $comment attributes give linting error in the CQL JSON Schema

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#581]
The duplicate $comment attributes give linting error when using spectral in the CQL JSON Schema. This also gives me a warning in VS Code. 

This can be resolved by making all the $comment fields unique. 

```
spectral lint cql.json --ruleset .spectral.yml
```

using .spectral.yml containing:

```
extends: "spectral:oas"
rules:
  oas3-api-servers: off
  oas3-schema: warn
  tag-description: true
  oas3-parameter-description: true
```
