### ISSUE TITLE
Features limit default

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/ogcapi-features#695]
The `limit` parameter for requesting features has the following schema fragment:

```yml
name: limit
in: query
required: false
schema:
  type: integer
  minimum: 1
  maximum: 10000
  default: 10
style: form
explode: false
```

I'm curious about the choice of a default of 10.  Since a feature collection is (typically) an unsorted collection, a request without a `limit` or other query parameters is typically the first in a series of requests to paginate through the entire collection.  Assuming 10 is a small number with respect to the entire feature collection size, a small page size is going to end up resulting in more work for everyone (client, server, the internet).

Would there be support for removing this `default` and leaving it up to services to decide on an appropriate default page size?
